disabled_rules:
  - todo
  - opening_brace
  - unneeded_synthesized_initializer

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - sorted_imports
  - comma
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - discouraged_optional_boolean
  - duplicate_imports
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - file_length
  - first_where
  - force_try
  - function_parameter_count
  - implicit_getter
  - implicitly_unwrapped_optional
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - mark
  - notification_center_detachment
  - operator_usage_whitespace
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_nil_coalescing
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unused_optional_binding
  - unused_setter_value
  - vertical_whitespace
  - void_return
  - weak_delegate
  - identifier_name
  - private_over_fileprivate
  - enum_case_associated_values_count
  - force_unwrapping
  - type_name
  - redundant_type_annotation
  - function_body_length
  - implicit_return
  - force_cast
  - switch_case_alignment
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - large_tuple

large_tuple:
  - 4
  - 3

switch_case_alignment:
  indented_cases: true

function_body_length:
  warning: 60
  error: 300
  
force_cast: warning

force_try: warning

legacy_hashing: error

collection_alignment:
  align_colons: true

force_unwrapping:
  severity: warning

implicit_return:
  included:
    - closure
    - getter

private_over_fileprivate:
  validate_extensions: true
  severity: error

redundant_type_annotation: error

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 60
  excluded:
    - Id

identifier_name:
  allowed_symbols: "_0123456789"
  min_length: 3
  max_length:
    warning: 60
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i

enum_case_associated_values_count:
  warning: 3
  error: 3

cyclomatic_complexity:
  warning: 10
  error: 20

line_length:
  warning: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

function_parameter_count:
  warning: 8
  error: 8

file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - fastlane
  - Pods
  - .bundle

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
