name: NeverForget
options:
  minimumXcodeGenVersion: 2.37.0
  groupSortPosition: top
  usesTabs: false
  generateEmptyDirectories: true
  indentWidth: 2
  tabWidth: 2
  xcodeVersion: 15.0
  localPackagesGroup: "Packages"
  deploymentTarget:
    iOS: "16.0"

################################################
# Settings
################################################
settings:
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: 1

################################################
# Packages
################################################
packages:
  SnapKit:
    url: "https://github.com/SnapKit/SnapKit.git"
    from: "5.6.0"
  SwiftDate:
    url: "https://github.com/malcommac/SwiftDate.git"
    from: "7.0.0"
  IQKeyboardManagerSwift:
    url: "https://github.com/hackiftekhar/IQKeyboardManager.git"
    from: "6.5.0"

  NFCore:
    path: "Packages/NFCore"
  NFLogger:
    path: "Packages/NFLogger"
  NFLocalNotificationsManager:
    path: "Packages/NFLocalNotificationsManager"
  NFCalendar:
    path: "Packages/NFCalendar"
  NFFormValidator:
    path: "Packages/NFFormValidator"

################################################
# Targets
################################################
targets:
  NeverForget:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: NeverForget
      CODE_SIGN_ENTITLEMENTS: "NeverForget/SupportingFiles/never-forget.entitlements"
      DEVELOPMENT_TEAM: 3LK6LB7235
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGN_STYLE: Automatic
      PRODUCT_BUNDLE_IDENTIFIER: com.urbans.neverforget

    configFiles:
      Debug: "configs/NeverForget-Debug.xcconfig"
      Release: "configs/NeverForget-Release.xcconfig"

    sources:
      - "NeverForget"

    dependencies:
      - package: SnapKit
      - package: SwiftDate
      - package: IQKeyboardManagerSwift

      - package: NFCore
      - package: NFLogger
      - package: NFLocalNotificationsManager
      - package: NFCalendar
      - package: NFFormValidator

    postCompileScripts:
      - path: "Scripts/swiftFormat.sh"
        name: ⚠️ SwiftFormat
        basedOnDependencyAnalysis: false
      - path: "Scripts/swiftLint.sh"
        name: ⚠️ SwiftLint
        basedOnDependencyAnalysis: false
